### ISSUE TITLE
 Capture mechanics.

### ISSUE THREAD

**Issue by MarcielMeurer** [sibiodev/zbxsmtptrap#1]
I didn't understand how the service will capture emails triggered for another account, including the service installed on the zabbix server.

Or is it mandatory to install the trap on the same veeam server?

I'm new, sorry me! I need more details to understand: D

**Comment by delahondes** [comment]
Hi Marciel, 

the email must be sent to the server where this code is installed, like for instance if the server with SMTP trap is called smtptrap.whatever.com (or is behind some firewall with that name that NAT all 25/10025 to 10025), then the email must be sent to zabbixhostname@smtptrap.whatever.com, where zabbixhostname is the name of the host linked to Veeam SMTP Trap template.

The code may live on Zabbix server, or not. In the later case, you'll have to change the ini file, here:
```ini
[zabbix]
port: 10051
address: 127.0.0.1
```

So nothing is to be installed on Veeam host. If you need the email to be sent to several people, you'll have to make an alias on a real mail server, send the email to this alias and put one of the member of the alias to zabbixhostname@smtptrap.whatever.com.

Raynald

**Comment by delahondes** [comment]
No news from you Marciel, I'm closing the issue.
