### ISSUE TITLE
Error when receive an email

### ISSUE THREAD

**Issue by viniciuscoelho** [sibiodev/zbxsmtptrap#2]
This is an expected error?

error: uncaptured python exception, closing channel <smtpd.SMTPChannel connected 209.85.215.194:38877 at 0x7f1a7c35e290> (<type 'exceptions.AttributeError'>:'error' object has no attribute 'msg' [/usr/lib64/python2.7/asyncore.py|read|83] [/usr/lib64/python2.7/asyncore.py|handle_read_event|449] [/usr/lib64/python2.7/asynchat.py|handle_read|158] [/usr/lib64/python2.7/smtpd.py|found_terminator|181] [/usr/lib/python2.7/site-packages/inbox.py|process_message|25] [/usr/local/bin/smtpToZbxTrap.py|handle|395] [/usr/local/bin/smtpToZbxTrap.py|send|155] [/usr/lib/python2.7/site-packages/pyzabbix/sender.py|send|433] [/usr/lib/python2.7/site-packages/pyzabbix/sender.py|_chunk_send|408])

**Comment by delahondes** [comment]
Hi Viniciuscoelho,
Can you send a larger log extract please? it seems the metrics are missing something, may be there is a clue in the log above. (or can you mimic the source email that did that so that I may reproduce)
Raynald

**Comment by viniciuscoelho** [comment]
Sorry, but I could make It work. The problem was the email content.
Everything is working fine now!

Thanks!!!

Em qua., 25 de mar. de 2020 às 06:18, Raynald de Lahondès <
notifications@github.com> escreveu:

**Comment by delahondes** [comment]
Ok thanks for the feedback Viniciuscoelho, so I close the issue.
